UI updated of WToggleSwitch
sugarlabs/musicblocks-2 pull request #298
Opened 2023-01-21 18:23 UTC by Tushar98644

2023-01-21 18:25 UTC, Tushar98644 commented
kindly review @meganindya

2023-01-21 18:27 UTC, Tushar98644 commented
> _ No description provided. _

<img width="1440" alt="Screenshot 2023-01-21 at 11 56 37 PM" src="https://user-images.githubusercontent.com/107763774/213881639-1de285d8-d00f-4421-92cc-9a093fa9a37d.png">
<img width="1440" alt="Screenshot 2023-01-21 at 11 56 50 PM" src="https://user-images.githubusercontent.com/107763774/213881641-bca80955-cddc-41dd-b904-cb21e82511c9.png">

2023-01-22 09:09 UTC, meganindya commented
[Contributing Guidelines](https://github.com/sugarlabs/musicblocks-v4/blob/develop/docs/CONTRIBUTING.md)

And please follow the mockup

2023-01-22 10:17 UTC, meganindya requested changes
I'd appreciate sticking to the naming convention specified in the issue. `WToggleSwitchRounded` for now.

2023-01-22 10:17 UTC, meganindya commented on src/common/components/index.ts
> +export { default as WToggleSwitch2 } from './WToggle-2';
insert between lines 1 and 2

2023-01-22 10:17 UTC, meganindya commented on src/common/components/WToggleSwitch/index.scss
> +}
this file shouldn't be a part

2023-01-22 10:17 UTC, meganindya commented on src/common/components/WToggle-2/index.stories.tsx
> +};
this doesn't align with storybook v7. I updated storybook from v6.5.15 to v7.0.0-beta.31

2023-01-22 10:17 UTC, meganindya commented on src/common/components/WToggle-2/index.scss
> +}
the dimensions don't match the mockup. Also please use color variables for white and grey.

2023-01-22 10:17 UTC, meganindya commented on src/common/components/WToggle-2/index.scss
> +        transform: translateX(-100%);
this might result in animation artefacts.

2023-01-22 10:18 UTC, meganindya commented
Please rebase on top of develop and squash down everything to one commit. You shouldn't merge default branch into a feature branch; always rebase.

2023-01-22 10:56 UTC, closed without merging